### ISSUE TITLE
Spotify modules doesn't work with latest version of Spotify

### ISSUE THREAD

**Issue by epaaj** [ultrabug/py3status#124]
The Spotify modules doesn't work with the latest version of Spotify.
There seems to have been som changes to the data in dbus.

**Comment by ultrabug** [comment]
ping @guilbep, mind looking into it mate ?

**Comment by jakubjedelsky** [comment]
fyi, I just found some release notes for [1.0.13](https://community.spotify.com/t5/Spotify-Community-Blog/Spotify-beta-1-0-13-for-Linux-released/ba-p/1197675):

- The application identifier is com.spotify.music, not com.spotify.qt
- The album artist field (xesam:albumArtist) is now respected and filled in if available
- The xesam:url property is now a proper URL (it was previously a Spotify URI)
- We no longer support the xesam:contentCreated field, sorry!
- The client does not yet send the PropertiesChanged signal to alert other applications that playback state has changed. This should be fixed in the next version.

**Comment by ultrabug** [comment]
@jakubjedelsky & @epaaj, mind trying @pydsigner's code and reporting if this fixes the issue ? I'm no spotify user so this would help a lot. Thx

**Comment by epaaj** [comment]
Those changes does not work for me. It still does not recognize that Spotify is running.
I got it to work with some changes of my own. But I'm a newbie when it comes to DBus.
See #130

**Comment by pydsigner** [comment]
@epaaj I'm not a DBus expert either (and don't plan on becoming one.....) but if that works for you then that's probably a good thing.

**Comment by ultrabug** [comment]
Fixed by @epaaj on MR #130 , thanks to everyone !
